services:
  - type: web
    name: knightbot-site
    runtime: node
    repo: https://github.com/Obitiko32/knight-bot-site
    plan: free
    buildCommand: |
      cd backend
      npm install
      pip install -r requirements.txt
    startCommand: |
      cd backend
      python app.py &
      node server.js
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: SITE_URL
        value: https://knightbot.lol
      - key: REDIRECT_URI
        value: https://knightbot.lol/auth/discord/callback
      - key: NODE_ENV
        value: production